import { JetBrains_Mono, Poppins } from "next/font/google";
import "./globals.css";

// Components
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Popup from "@/components/Popup";

export const metadata = {
  title: "DemoApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Popup />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
